[package]
name = "ticket-auction"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "2.0.0"
cosmwasm-std = { version = "1.5.0" }
terraswap = "2.4.0"
terra-cosmwasm = "2.2.0"
mirror-protocol = "2.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
